backend:
  name: git-gateway
  branch: master
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false, hint: "La URL amigable. Si se deja en blanco, se genera a partir del título." }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Categoría", name: "category", widget: "relation", collection: "categories", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
      - { label: "Tags", name: "tags", widget: "relation", collection: "tags", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: true }
      - { label: "Imagen de Miniatura", name: "thumbnail", widget: "image", required: false }
      - { label: "Meta Título (SEO)", name: "meta_title", widget: "string", required: false, hint: "Título para buscadores. Recomendado: 50-60 caracteres." }
      - { label: "Meta Descripción (SEO)", name: "meta_description", widget: "string", required: false, hint: "Descripción para buscadores. Recomendado: 150-160 caracteres." }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false, hint: "La URL amigable. Si se deja en blanco, se genera a partir del título." }
      - { label: "Meta Título (SEO)", name: "meta_title", widget: "string", required: false, hint: "Título para buscadores. Recomendado: 50-60 caracteres." }
      - { label: "Meta Descripción (SEO)", name: "meta_description", widget: "string", required: false, hint: "Descripción para buscadores. Recomendado: 150-160 caracteres." }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false, hint: "La URL amigable. Si se deja en blanco, se genera a partir del título." }
      - { label: "Meta Título (SEO)", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Descripción (SEO)", name: "meta_description", widget: "string", required: false }
      - { label: "Descripción", name: "description", widget: "string", required: false, hint: "Descripción corta que aparece en la parte superior de la página de la categoría." }
      - { label: "Contenido", name: "content", widget: "markdown", required: false, hint: "Contenido adicional que aparece debajo de la lista de posts." }
  - name: "tags"
    label: "Tags"
    folder: "content/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false, hint: "La URL amigable. Si se deja en blanco, se genera a partir del título." }
      - { label: "Meta Título (SEO)", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Descripción (SEO)", name: "meta_description", widget: "string", required: false }
      - { label: "Descripción", name: "description", widget: "string", required: false, hint: "Descripción corta que aparece en la parte superior de la página de la etiqueta." }
      - { label: "Contenido", name: "content", widget: "markdown", required: false, hint: "Contenido adicional que aparece debajo de la lista de posts." }
  - name: "code_snippets"
    label: "Insertar Código"
    folder: "content/code_snippets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string", hint: "Un nombre para identificar este snippet, ej: Google Tag Manager" }
      - { label: "Código para <head>", name: "head_code", widget: "code", required: false, hint: "Pega aquí el código que debe ir en la etiqueta <head> de todas las páginas." }
      - { label: "Código para <body>", name: "body_code", widget: "code", required: false, hint: "Pega aquí el código que debe ir justo después de la apertura de la etiqueta <body>." }
